package com.ariix.base64;

import java.util.Base64;
import java.util.Base64.Decoder;

public class DecoderUtils {

	public static void main(String[] args) {
		Decoder base64Decoder = Base64.getDecoder();
		byte[] bytes = base64Decoder.decode("PGh0bWw+CjxoZWFkPgogICAgPG1ldGEgaHR0cC1lcXVpdj0iY29udGVudC10eXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJzZXQ9VVRGLTgiPgogICAgPHNjcmlwdCBzcmM9Imh0dHBzOi8vYWpheC5nb29nbGVhcGlzLmNvbS9hamF4L2xpYnMvanF1ZXJ5LzEuNy4yL2pxdWVyeS5taW4uanMiPjwvc2NyaXB0PgogICAgPHN0eWxlIHR5cGU9InRleHQvY3NzIj4KCiAgICAgICAgLypDU1MgUkVTRVQgaW4gb3JkZXIgdG8gYXZvaWQgdXNlciBhZ2VudCBhZGRlZCBzdHlsZXNoZWV0Ki8KICAgICAgICBodG1sLCBib2R5LCBkaXYsIHNwYW4sIGFwcGxldCwgb2JqZWN0LCBpZnJhbWUsCiAgICAgICAgaDEsIGgyLCBoMywgaDQsIGg1LCBoNiwgcCwgYmxvY2txdW90ZSwgcHJlLAogICAgICAgIGEsIGFiYnIsIGFjcm9ueW0sIGFkZHJlc3MsIGJpZywgY2l0ZSwgY29kZSwKICAgICAgICBkZWwsIGRmbiwgZW0sIGltZywgaW5zLCBrYmQsIHEsIHMsIHNhbXAsCiAgICAgICAgc21hbGwsIHN0cmlrZSwgc3Ryb25nLCBzdWIsIHN1cCwgdHQsIHZhciwKICAgICAgICBiLCB1LCBpLCBjZW50ZXIsCiAgICAgICAgZGwsIGR0LCBkZCwgb2wsIHVsLCBsaSwKICAgICAgICBmaWVsZHNldCwgZm9ybSwgbGFiZWwsIGxlZ2VuZCwKICAgICAgICB0YWJsZSwgY2FwdGlvbiwgdGJvZHksIHRmb290LCB0aGVhZCwgdHIsIHRoLCB0ZCwKICAgICAgICBhcnRpY2xlLCBhc2lkZSwgY2FudmFzLCBkZXRhaWxzLCBlbWJlZCwKICAgICAgICBmaWd1cmUsIGZpZ2NhcHRpb24sIGZvb3RlciwgaGVhZGVyLAogICAgICAgIG1lbnUsIG5hdiwgb3V0cHV0LCBydWJ5LCBzZWN0aW9uLCBzdW1tYXJ5LAogICAgICAgIHRpbWUsIG1hcmssIGF1ZGlvLCB2aWRlbyB7CiAgICAgICAgICAgIG1hcmdp");
		String clearStr = new String(bytes);
		System.out.println(clearStr);
	}

}
